.github/workflows/npm-app-build.yml
.github/workflows/npm-app-release-with-docs.yml
.github/workflows/npm-app-release.yml
.github/workflows/npm-app-snapshot-release.yml
.github/workflows/npm-lib-build.yml
.github/workflows/npm-lib-release.yml
.github/workflows/npm-lib-snapshot.yml

Some `container: ` properties on jobs were still using node v14. Based on [this search of the Zepben org](https://github.com/search?q=org%3Azepben+path%3Apackage.json+engine+OR+volta&type=code), all our repos require at least node v16.
This became a problem in https://github.com/zepben/ednar-web-client/pull/313, where the `npm ci` command [failed to install dependencies](https://github.com/zepben/ednar-web-client/actions/runs/7001189759/job/19042924046?pr=313#step:10:10) after the addition of `Playwright`.
After looking this issue up online, I found [this Stack Overflow post](https://stackoverflow.com/a/69121224) that mentioned similar issues if the `package-lock.json` file was v2 while `npm` was <v7. This is indeed the case when running `node` v14, where we get `npm `v6 (see docs …

Upgrade all Node job containers to `node:16-alpine`

---

.github/workflows/npm-app-release.yml

This change will set an environment variable `HUSKY` to 0 during the ci run to disable pre-commit hooks via husky. At this stage, CI doesn't require these hooks to run.
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.
~- [ ] I have rebased onto the target branch (usually main).~

Disable husky for CI

---

.github/workflows/csharp-app-snapshot.yml
.github/workflows/csharp-build.yml
.github/workflows/maven-app-snapshot.yml
.github/workflows/maven-build-oss.yml
.github/workflows/maven-build.yml
.github/workflows/maven-lib-snapshot.yml
.github/workflows/npm-app-build.yml
.github/workflows/npm-app-snapshot-release.yml
.github/workflows/npm-lib-build.yml
.github/workflows/npm-lib-snapshot.yml
.github/workflows/python-build.yml
.github/workflows/python-lib-snapshot.yml
workflow-templates/csharp-app-snapshot.yml
workflow-templates/maven-app-snapshot.yml
workflow-templates/maven-lib-snapshot.yml
workflow-templates/npm-app-snapshot-release.yml
workflow-templates/npm-lib-snapshot-release.yml
workflow-templates/python-lib-snapshot.yml

* Add docs building and deployment to all snapshot releases. It's done without tagging a new version; i.e. the deployment will update the "next" version only.
* Switch all docs building to node-20
* Update the old ways to output in GH actions with the new one ($GITHUB_OUTPUT)
* Cleanup unused code
* Replace TAG-AND-RELEASE flag to docs building with TAG.
* Update all templates with the product-key example.
https://github.com/zepben/docusaurus-action/pull/7
~ [x] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~ …

Docs building and deployments updates

---

.github/workflows/csharp-app-release-with-docs.yml
.github/workflows/maven-app-release-with-docs.yml
.github/workflows/maven-lib-release-with-docs.yml
.github/workflows/npm-app-build.yml
.github/workflows/npm-app-release-with-docs.yml
.github/workflows/npm-app-release.yml
.github/workflows/npm-app-snapshot-release.yml
.github/workflows/npm-lib-build.yml
.github/workflows/npm-lib-release.yml
.github/workflows/npm-lib-snapshot.yml
.github/workflows/python-lib-release-with-docs.yml

Use node20 to build all node projects (docs and front-end). Some have been reverted to 14 by mistake due to possible merge conflicts; others are on 16 and some are on 20.
This aligns all of them.

Align node versions

---

.github/workflows/csharp-app-snapshot.yml
.github/workflows/maven-app-snapshot.yml
.github/workflows/maven-lib-snapshot.yml
.github/workflows/npm-app-snapshot-release.yml
.github/workflows/npm-lib-snapshot.yml
.github/workflows/python-lib-snapshot.yml

1.  Product-key and product-repo are no longer necessary.
1. If provided, the product key will be used as a doc component name for deployment (usable for i.e. SDK docs where the component name is different from the repo name)
1. If not provided, the product key will be parsed from the docs/docusaurus.config.js file.
1. The repo is always automatically detected (so at the moment, product-repo will be ignored. Next step will be to clean it up from the configurations already updated)
~- [ ] I have commented my code in any …

Simplify snapshots with docs

---

.github/workflows/npm-app-build.yml
.github/workflows/npm-app-snapshot-release.yml
.github/workflows/npm-lib-build.yml
.github/workflows/npm-lib-snapshot.yml

We've possibly never run the licensecheck for some of the npm projects, so didn't hit the issue before. Adding bash to node20 image as that's what licensecheck uses.

Fixing the npm container to run the licencecheck; adding bash to it

---

.github/workflows/npm-lib-release.yml
.github/workflows/npm-lib-snapshot.yml

Since upgrading to Node v20, which includes NPM v10.5, the `npm pack` command has begun outputting `stdout` from the project's `prepare` script as well (see ticket for more info). This broke the way we were capturing the artifact filename, so we need a workaround.
Since `npm pack` runs quickly, we thought it would be okay to run it twice - once for logging purposes on CI (and actually packing the artifact), and once again for parsing the artifact name (silent to CI logs).
None

[OPS-201] Fix mangled artifact name in npm-lib-snapshot/release workflows

---

.github/workflows/csharp-app-release-with-docs.yml
.github/workflows/maven-app-release-with-docs.yml
.github/workflows/maven-lib-release-with-docs.yml
.github/workflows/npm-app-release-with-docs.yml
.github/workflows/npm-app-release.yml
.github/workflows/python-lib-release-with-docs.yml

This fix syncs the work done previously for the snapshot flows where "product-key" value is automatically detected from docs/docusaurus.conf.js to all other release-with-docs flows.
If the repo using any of these flows deploys documentation to a custom-named site, "product-key" can be overwritten in the appropriate github action in the repo.

Make product-key optional

---

.github/workflows/csharp-app-release-with-docs.yml
.github/workflows/maven-app-release-with-docs.yml
.github/workflows/maven-lib-release-with-docs.yml
.github/workflows/npm-app-release-with-docs.yml
.github/workflows/python-lib-release-with-docs.yml

Zip docs before uploading them as artefacts so that docs deployment can find them.
~- [ ] I have considered if this is a breaking change and will communicate it with other team members if so.~

Zipping docs before artefact upload in release workflows

---

.github/workflows/csharp-app-release-with-docs.yml
.github/workflows/maven-app-release-with-docs.yml
.github/workflows/maven-lib-release-with-docs.yml
.github/workflows/npm-app-release-with-docs.yml
.github/workflows/python-lib-release-with-docs.yml

We do not need to attach docs site to the release anymore as the deployment happens via a different repo action.
~- [ ] I have considered if this is a breaking change and will communicate it with other team members if so.~

Do not attach docs to release

---

.github/workflows/maven-lib-release-with-docs.yml
.github/workflows/maven-lib-release.yml
.github/workflows/maven-lib-snapshot.yml

Pin the leftover `pipeline-java` containers missed in #38  to version 4.4.0.

Pin leftover pipeline-java containers to 4.4.0

---

.github/workflows/csharp-app-release-with-docs.yml
.github/workflows/csharp-app-release.yml
.github/workflows/csharp-app-snapshot.yml
.github/workflows/maven-app-release.yml
.github/workflows/maven-app-snapshot.yml
.github/workflows/npm-app-release-with-docs.yml
.github/workflows/npm-app-release.yml
.github/workflows/npm-app-snapshot-release.yml

I'm working on some docker image build workflows that would allow us to easily have containers built/tagged in a consistent way. In order to have consistent tagging, I want to reuse the version numbers that we use when building releases/snapshots etc. 
This PR adds the version as outputs to all reusable workflows that build apps. Recommend reviewing while hiding whitespace since VScode removed alot of the extra spaces floating around.
In production lol

Add version output to all app CI jobs

---

.github/workflows/npm-app-release.yml

We store the last segment of the changelog.md in a variable. It includes `*` sign (for example, `* None`); when later used without quotes, it globs and shell fills in all the files in the local directory and removes all the new lines.
This fix quotes the variable and allows to use it literally.
The release in a  test repo https://github.com/zepben/npm-app-ci-test/releases/tag/v1.25.0 was built with this branch.
~- [ ] I have handled all new warnings …

[OPS-254] Fix latest changelog parameter for shell expansion

---

.github/workflows/maven-lib-release-with-docs.yml
.github/workflows/maven-lib-release.yml

Upload and download artefact versions have to be the same to work properly.

[OPS-257] Sync upload and download artefact versions for maven lib release

---

.github/workflows/build-sealed-docker-image-public.yml
.github/workflows/build-sealed-docker-image.yml

Similar to #49, but adds a workflow that doesn't log into any of our private repos so that we can used it to build images in public repos

Add sealed image workflow for public repos

---

.github/workflows/build-sealed-docker-image-public.yml
.github/workflows/build-sealed-docker-image.yml

When overriding the commit and dispatching the docker build we need to ensure the final image is tagged correctly. In order to do this, we need to tell the build to use git as the source of truth instead of the workflow event.

Fix invalid tags on docker image

---

.github/workflows/build-sealed-docker-image-public.yml
.github/workflows/build-sealed-docker-image.yml

Reverts #57. Seems there is an issue with fetching the git details when in detached mode. So instead we compute the git sha ourselves. There appears to be a closed issue regarding this in the metadata action repository, but no solution or workaround (https://github.com/docker/metadata-action/issues/362)

Manually resolve git tags for docker image builds

---

.github/workflows/build-sealed-docker-image-public.yml
.github/workflows/build-sealed-docker-image.yml

Follow up to #58, the PR:
- Fixes the Get SHA step to return the correct long sha, instead of `checkout.ref` since it is not set on branches
- Allows supression of sha-based tags, useful for builds that have bundled containers (EAS/UI)
- Add the open container vendor tag

Fix container builds to use correct tags

---

.github/workflows/python-lib-release-with-docs.yml
.github/workflows/python-lib-release.yml

When we release our python packages, we strip all snapshot versions from the project, including itself AND various dependencies. To make sure those dependencies have been actually released, we want to fail build here if they haven't been, so this PR is adding a step in the workflow that basically will try to install all those dependencies and fail if they are not present.

[OPS-262] Fail python build quickly if not all dependencies are available

---

.github/workflows/maven-app-release-with-docs.yml
.github/workflows/maven-app-release.yml
.github/workflows/maven-app-snapshot.yml

Allow for Maven repos using the `maven-app-release.yml`, `maven-app-release-with-docs.yml`, and `maven-app-snapshot.yml` workflows to support outputting multiple files as artifacts and release assets, rather than a single JAR file.
This is done in a backwards-compatible way with repos that expect to output a single JAR. When a maven project is built, it produces a `target/` folder that looks roughly like this:
```
classes/
coverage-reports/
generated-sources/
generated-test-sources/
kotlin-ic/
maven-status/
site/
surefire-reports/
test-classes/
**project-version.jar**
original-project-version.jar
```
Under the old workflows, **project-version.jar** would be identified as the build artifact and attached as a release asset.
With these changes, every file in the top-level of the `target/` …

Ops 279 multiple artifacts maven

---

.github/workflows/csharp-app-release-with-docs.yml
.github/workflows/csharp-app-release.yml
.github/workflows/maven-app-release-with-docs.yml
.github/workflows/maven-app-release.yml
.github/workflows/maven-lib-release-with-docs.yml
.github/workflows/maven-lib-release.yml
.github/workflows/npm-app-release-with-docs.yml
.github/workflows/npm-lib-release.yml
.github/workflows/python-lib-release-with-docs.yml

We still have a few workflows that sometimes get error 141 in bash when generating the latest_changelog entry. This is caused by a racing condition in bash between the parts of the pipeline, and it's hard to catch.
This patch reworks the functionality to use 1 command in attempt to avoid this error in the future. This way of generating the latest_changelog is already used in `npm-lib` workflows.
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.
~- [ ] I have commented my code in any hard-to-understand or hacky areas.
~- [ ] I have handled all new warnings generated by the compiler or IDE.
Not a breaking change - the …

[OPS-299] Fix error 141 in latest_changelog generation

---

misc/repos-config/branch-protection-rules.json
misc/repos-config/set-branch-protection-rules.sh

Adding branch protection via `gh` to a bunch of repositories.
This is just a location for the script, not trying to make it "production-ready"
Tested on `mvn-lib-ci-test`, `mvn-app-ci-test` and `npm-app-ci-test` repositories.

[OPS-277] Add script to create branch protection rules for repositories

---

.github/workflows/maven-app-release-with-docs.yml

Fix the `create-release` job in the `maven-app-release-with-docs` flow to include all files in the artefact path when uploading files for a release.
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not, just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
Tested in the `mvn-app-ci-test` repository
https://github.com/zepben/mvn-app-ci-test/actions/runs/14234846634/job/39892351237
~- [ ] I have added/updated unit tests for these changes, and if not I have …

[OPS-313] Upload all artefacts for a release

---

.github/workflows/csharp-app-release-with-docs.yml
.github/workflows/maven-app-release-with-docs.yml
.github/workflows/maven-app-release.yml
.github/workflows/maven-lib-release-with-docs.yml
.github/workflows/maven-lib-release.yml
.github/workflows/npm-app-release-with-docs.yml
.github/workflows/python-lib-release-with-docs.yml
.github/workflows/python-lib-release.yml

We checked the proper format of the changelog in the `release-check` step for most of the repos; however, we did not export the result of that check as an output, so during the release creation, there were no files to add as notes. This change restores the 'changelog' output in the `release-checks` job, passing it along to the `release` step.
This is not a breaking change.

[OPS-314] Add 'changelog' output parameter to release-checks job

---

.github/workflows/npm-app-build.yml
.github/workflows/npm-app-snapshot-release.yml
.github/workflows/npm-lib-build.yml
.github/workflows/npm-lib-snapshot.yml

The `node:20` runner containers do not have `gh` installed, this change fixes that.
Not a breaking change.

[OPS-340] Fix node:20 runner containers

---

.github/workflows/csharp-app-snapshot.yml
.github/workflows/csharp-build.yml

At the moment we have a couple of C#-related workflows where the repo checks (licence check, docs presence and whether some build docusaurus files are added to .gitignore) are run within the build job, which runs the Windows container. This host cannot run these checks.
This change splits  the repo checks out into a separate job, and keeps Windows host for building and testing C# only.
Not  a breaking change.

[OPS-355] Split repo check and build workflows for csharp

---

.github/workflows/maven-build.yml

Add a check to maven PR builds so that incorrect SNAPSHOT naming usage can't be merged.
A slighly breaking change - projects that use `-SNAPSHOT` in their version will fail the maven build. They will need to be updated to use `b` instead.

[OPS-407] Add a check to maven PR builds so that incorrect SNAPSHOT naming usage can't be merged

---

.github/workflows/csharp-build.yml
.github/workflows/maven-build-oss.yml
.github/workflows/maven-build.yml
.github/workflows/npm-app-build.yml
.github/workflows/npm-lib-build.yml
.github/workflows/python-build.yml

This PR adds the check for secrets leaks to all the `-build` workflows.
If the check finds leaked secrets, it will comment on the code, and an additional PR comment will be made pointing to the action summary. 
PR comments will bug people until the commit with the leak is no longer present in the branch's history. 
This is currently configured with a very low entropy, so it may find many false positives. We might need to update the config if that happens.

[OPS-320] gitleaks setup

---

.github/workflows/csharp-build.yml
.github/workflows/maven-build-oss.yml
.github/workflows/maven-build.yml
.github/workflows/npm-app-build.yml
.github/workflows/npm-lib-build.yml
.github/workflows/python-build.yml

Disable artefact uploading in Gitleaks, as we're running in a container. When that happens, Gitleaks is unable to detect the artefact directory structure properly, so we skip it altogether - we only actually need the information about the leaks.

Disable artifact uploading in gitleaks as we're running in a custom container

---

.github/workflows/csharp-app-release.yml
.github/workflows/maven-app-release.yml
.github/workflows/maven-lib-release.yml
.github/workflows/npm-app-release.yml
.github/workflows/python-lib-release.yml
misc/repos-config/set-branch-protection-rules.sh

Enough is enough. 
We have 2 flows for releases: the regular release and `with-docs`. There's no functional difference between the 2 (except for the docs deployment), so we're retiring one out of each pair.
This is *Stage 1*. This change essentially synchronises all the flows, allowing both `-with-docs` and regular flows to function identically, building documents if the folder exists. 
Next, we're going to update all the repositories using the `-with-docs` workflows to use the regular workflows for releases.
Finally, in *Stage 2* we will be deleting all the `-with-docs` flows.
This order of deployment will minimise the breaking of the releases for all parties involved.
Not a breaking change in itself.

[EWB-4093] 'release-with-docs' flows are going away. Enough is enough
