- .github/workflows/csharp-app-release.yml
- .github/workflows/csharp-app-snapshot.yml
- .github/workflows/csharp-build.yml
- .github/workflows/csharp-hotfix-branch.yml
- .github/workflows/csharp-lts-branch.yml
- .github/workflows/maven-hotfix-branch.yml
- .github/workflows/maven-lts-branch.yml
- .github/workflows/npm-hotfix-branch.yml
- .github/workflows/npm-lts-branch.yml
- .github/workflows/python-hotfix-branch.yml
- .github/workflows/python-lts-branch.yml
- workflow-templates/csharp-app-build.properties.json
- workflow-templates/csharp-app-build.yml
- workflow-templates/csharp-app-release.properties.json
- workflow-templates/csharp-app-release.yml
- workflow-templates/csharp-app-snapshot.properties.json
- workflow-templates/csharp-app-snapshot.yml
- workflow-templates/csharp-hotfix-branch.properties.json
- workflow-templates/csharp-hotfix-branch.yml
- workflow-templates/csharp-lts-branch.properties.json
- workflow-templates/csharp-lts-branch.properties.yml
A summary of the changes and what they achieve. If there is a click up task with decent detail associated with this change the summary can be brief, otherwise please add some motivation and context here.
If you have added new depedencies to the project please state why. 
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not just add an appropriate note here so reviewers know there is a dependecny and will hold off merging until all things are ready.
> Ops 143 create centralised workflows for c apps

- workflow-templates/maven-app-release-with-docs.yml
- workflow-templates/maven-app-snapshot.yml
Signed-off-by: Alex Lourie <alex.lourie@zepben.com>
> Use 'private: true' by default in all maven templates

- .github/workflows/maven-lib-release-with-docs.yml
Update node version when building docusaurus docs.
> Update node version to 14 for doc building

- .github/workflows/csharp-app-release.yml
- .github/workflows/csharp-app-snapshot.yml
- .github/workflows/csharp-build.yml
- .github/workflows/csharp-hotfix-branch.yml
- .github/workflows/csharp-lts-branch.yml
- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build-oss.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-hotfix-branch.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
- .github/workflows/maven-lts-branch.yml
- .github/workflows/npm-app-build.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/npm-app-release.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-hotfix-branch.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/npm-lib-release.yml
- .github/workflows/npm-lib-snapshot.yml
- .github/workflows/npm-lts-branch.yml
- .github/workflows/python-build.yml
- .github/workflows/python-hotfix-branch.yml
- .github/workflows/python-lib-release-with-docs.yml
- .github/workflows/python-lib-release.yml
- .github/workflows/python-lib-snapshot.yml
- .github/workflows/python-lts-branch.yml
Versions bump for all builtin GH actions.
> Bump all github action versions to latest stable

- .github/workflows/csharp-app-release-with-docs.yml
- .github/workflows/csharp-build.yml
- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-build-oss.yml
- .github/workflows/maven-build.yml
- .github/workflows/npm-app-build.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/python-build.yml
- .github/workflows/python-lib-release-with-docs.yml
> Ewb 4089 build docs as part of all workflows

- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/python-lib-release-with-docs.yml
Parse the changelog and only include last section in release notes
> Parse the changelog and only include last section in release notes

- .github/workflows/csharp-app-release-with-docs.yml
- .github/workflows/csharp-app-release.yml
- .github/workflows/csharp-app-snapshot.yml
- .github/workflows/csharp-build.yml
- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
- .github/workflows/npm-app-build.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/npm-app-release.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/npm-lib-release.yml
- .github/workflows/npm-lib-snapshot.yml
- .github/workflows/python-build.yml
- .github/workflows/python-lib-release-with-docs.yml
- .github/workflows/python-lib-release.yml
Makes license check optional and defaults to true if not provided. This potentially might lead to failing pipelines where this is not properly setup, but we'll deal with them as they come.
> Make license check optional

- .github/workflows/csharp-app-release-with-docs.yml
- .github/workflows/csharp-app-release.yml
- .github/workflows/csharp-app-snapshot.yml
- .github/workflows/csharp-build.yml
- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
- .github/workflows/npm-app-build.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/npm-app-release.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/npm-lib-release.yml
- .github/workflows/npm-lib-snapshot.yml
- .github/workflows/python-build.yml
- .github/workflows/python-lib-release-with-docs.yml
- .github/workflows/python-lib-release.yml
To perform licence check we use an input parameter, which is of type _boolean_. However, later in the flow we set an env variable with its value, actually turning it into the string, but then we compare it to a boolean again to run or skip the check.
This change removes using the env variable and uses the input value (boolean) as is, performing boolean comparisons.
-~ [ ] I have updated any documentation required for these changes.~
> Ops 191 fix licence check

- .github/workflows/npm-app-build.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/npm-lib-snapshot.yml
Curl is missing from node:20 and required by the licence check
> Add curl for the licencecheck

- .github/workflows/csharp-app-release-with-docs.yml
- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/python-lib-release-with-docs.yml
Adding zip to node container and switching to sh exec for docs building
> Adding zip to node container and switching to sh exec for docs building

- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build-oss.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-hotfix-branch.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
- .github/workflows/maven-lts-branch.yml
Pin `pipeline-java` container to version 4.4.0 and bump `checkout` action to v4 for all maven actions.
- x ] I have rebased onto the target branch (usually main).
> Ops 215 pin java container

- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build-oss.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
Bump pipeline-java container to the new version `4.5.0`.
Use a test repository to run this branch for the maven-build flow manually. The flow should finish successfully.
> Bump pipeline-java container version

- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build-oss.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
Bump maven flows to pipeline-java:4.5.1
> Bump pipeline-java version

- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build-oss.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
> Bump pipeline-java version to 4.5.2

- .github/workflows/csharp-app-release-with-docs.yml
- .github/workflows/csharp-app-release.yml
- .github/workflows/csharp-app-snapshot.yml
- .github/workflows/csharp-build.yml
- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
- .github/workflows/npm-app-build.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/npm-app-release.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/npm-lib-release.yml
- .github/workflows/npm-lib-snapshot.yml
- .github/workflows/python-build.yml
- .github/workflows/python-lib-release-with-docs.yml
- .github/workflows/python-lib-release.yml
Removing licence check conditional - this is a **_breaking change_** that will force licence check in all our repositories that use these workflows.
It means all repositories that supply this parameter will fail build and will need updating.
> Licence check is no longer optional - BREAKING CHANGE

- .github/workflows/csharp-app-release-with-docs.yml
- .github/workflows/csharp-app-release.yml
- .github/workflows/csharp-hotfix-branch.yml
- .github/workflows/csharp-lts-branch.yml
- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-hotfix-branch.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
- .github/workflows/maven-lts-branch.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/npm-app-release.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-hotfix-branch.yml
- .github/workflows/npm-lib-release.yml
- .github/workflows/npm-lib-snapshot.yml
- .github/workflows/npm-lts-branch.yml
- .github/workflows/python-hotfix-branch.yml
- .github/workflows/python-lib-release-with-docs.yml
- .github/workflows/python-lib-release.yml
- .github/workflows/python-lib-snapshot.yml
- .github/workflows/python-lts-branch.yml
This is just a version bump to use pipeline containers with better commit messages.
> [OPS-238] Bump pipelines to newer container versions

- .github/workflows/csharp-app-release-with-docs.yml
- .github/workflows/csharp-app-release.yml
- .github/workflows/csharp-hotfix-branch.yml
- .github/workflows/csharp-lts-branch.yml
- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-hotfix-branch.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
- .github/workflows/maven-lts-branch.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/npm-app-release.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-hotfix-branch.yml
- .github/workflows/npm-lib-release.yml
- .github/workflows/npm-lib-snapshot.yml
- .github/workflows/npm-lts-branch.yml
- .github/workflows/python-hotfix-branch.yml
- .github/workflows/python-lib-release-with-docs.yml
- .github/workflows/python-lib-release.yml
- .github/workflows/python-lib-snapshot.yml
- .github/workflows/python-lts-branch.yml
Bump pipeline-basic version to updates to commit messages. 
https://app.clickup.com/t/6929263/OPS-239
> Bump pipleline-basic version

- .github/workflows/npm-app-build.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/npm-app-release.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/npm-lib-release.yml
- .github/workflows/npm-lib-snapshot.yml
Seems we have a few hardcoded NPM registry urls in the workflows. This PR updates them to the shiny new one.
> Update Npm urls to point to new nexus

- .github/workflows/csharp-app-release-with-docs.yml
- .github/workflows/csharp-app-release.yml
- .github/workflows/csharp-hotfix-branch.yml
- .github/workflows/csharp-lts-branch.yml
- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-hotfix-branch.yml
- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
- .github/workflows/maven-lts-branch.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/npm-app-release.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-hotfix-branch.yml
- .github/workflows/npm-lib-release.yml
- .github/workflows/npm-lib-snapshot.yml
- .github/workflows/npm-lts-branch.yml
- .github/workflows/python-hotfix-branch.yml
- .github/workflows/python-lib-release-with-docs.yml
- .github/workflows/python-lib-release.yml
- .github/workflows/python-lib-snapshot.yml
- .github/workflows/python-lts-branch.yml
> Bump basic pipeline to 5.7.5

- .github/workflows/build-sealed-docker-image.yml
'Hermetically Sealed Docker builds' are what I and a colleague called it when you configure a Dockerfile so that you can simply run `docker build .` (mostly) to allow an application to be built into a runnable state. This allows end users run the application without having anything more than Docker installed (mostly). This has been a preference of mine since it makes it easy to get up and running. 
This sort of pattern also has the added benefit of knowing 1. Exactly what it takes to build your application, 2. Exactly what it takes to run your application. Our previous Docker builds were done with Packer and I found two issues with them
1. Docker native features - The Dockerfile syntax has evolved for a while now and it seems as though they weren't available or not used in the packer …
> Hermetically Sealed Docker Image Build Workflow

- .github/workflows/build-sealed-docker-image.yml
Nuget sources may persist, so we need to try remove then add it just in case
> [Fix] Remove Nuget source before adding

- .github/workflows/maven-app-release-with-docs.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lts-branch.yml
Populate `nexus.signature` value in maven config using gh secret.
~- [] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~
Not a breaking change.
> [OPS-287] Add custom header to maven requests

- .github/workflows/build-sealed-docker-image.yml
Add Nexus signature to env when running maven-login action.
Not a breaking change.
> [OPS-289] Add nexus signature to maven-login

- .github/pull_request_template.md
> Updated PR template to tell the developer to post any breaking changes in the 'breaking-changes' Slack channel.

- .github/workflows/csharp-app-snapshot.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build-oss.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-lib-snapshot.yml
- .github/workflows/npm-app-build.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/npm-lib-snapshot.yml
- .github/workflows/python-build.yml
- .github/workflows/python-lib-snapshot.yml
Provide a proper gh context for all licence checks
Not a breaking change.
> [OPS-338] Provide a proper gh context for all licence checks

- .github/workflows/csharp-app-snapshot.yml
- .github/workflows/csharp-build.yml
- .github/workflows/maven-app-snapshot.yml
- .github/workflows/maven-build-oss.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-lib-snapshot.yml
- .github/workflows/npm-app-build.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/npm-lib-snapshot.yml
- .github/workflows/python-build.yml
- .github/workflows/python-lib-snapshot.yml
Fix git permissions before running licencecheck
> Fixing git permissions

- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
Update MAVEN_CENTRAL username and password for the `ossrh` -> `maven central` migration.
Related PRs:
- https://github.com/zepben/ci-utils/pull/30
- https://github.com/zepben/maven-deploy-central-action/pull/6
- https://github.com/zepben/ewb-super-pom/pull/58
This change is breaking and has to be merged as a concerned effort together will other tasks in the related list; otherwise …
> [OPS-369] Update MAVEN_CENTRAL username and password

- .github/workflows/maven-lib-release-with-docs.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/maven-lib-snapshot.yml
Fixing ossrh->maven profile name
> Fixing ossrh->maven profile name

- .github/workflows/dependencies-check.yml
Add a new workflow to perform the internal dependency chain check.
> Dependency check workflow

- .github/workflows/dependencies-check.yml
Issues fixed for dependency check comment:
- Header line excluded
- Code block makes it easier to read, since it was originally formatted for monospaced text
- line width increased 80 &rarr; 120 chars to avoid issues with line being split
No blocking nor blocked tasks
Run workflow on some zepben PR
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~ (tested manually)
No breaking changes.
Remove this section if the change cannot be shown through screenshots. Frontend changes …
> Improve dependency check comment

- .github/workflows/csharp-build.yml
- .github/workflows/maven-build-oss.yml
- .github/workflows/maven-build.yml
- .github/workflows/npm-app-build.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/python-build.yml
> Temporarily go back to default config

- .github/workflows/csharp-app-release.yml
- .github/workflows/csharp-build.yml
- .github/workflows/maven-app-release.yml
- .github/workflows/maven-build-oss.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-lib-release.yml
- .github/workflows/npm-app-build.yml
- .github/workflows/npm-app-release-with-docs.yml
- .github/workflows/npm-app-release.yml
- .github/workflows/npm-app-snapshot-release.yml
- .github/workflows/npm-lib-build.yml
- .github/workflows/python-build.yml
- .github/workflows/python-lib-release.yml
Use new docusaurus build pipeline.
> [OPS-428] Use docusaurus build in new pipeline

- .github/workflows/python-build.yml
- .github/workflows/python-hotfix-branch.yml
- .github/workflows/python-lib-release-with-docs.yml
- .github/workflows/python-lib-release.yml
- .github/workflows/python-lib-snapshot.yml
- .github/workflows/python-lts-branch.yml
> Move python builds to 3.10

- .github/workflows/npm-app-release.yml
The `create-release` step in the `npm-app-release` was missing a dependency; this led to incorrect parsing of the previously generated version and changelog information. This resulted in incorrect release versioning and lack of proper changelog notes.
This change fixed the dependency. 
When developing applications, use following guidelines for information security considerations:
* Access to applications should be protected with security keys/tokens or usernames and passwords;
* All sessions are encrypted if possible;
* All application input is sanitised before being acted on (ie SQL statements, etc);
* Log messages, and especially client-facing ones, must be handled securely and must not leak credentials information (internal URLs, passwords, tokens).
Unrelated to security.
Not a …
> Fix a dependency in npm-app-release workflow
